require('plugins')
require('settings')
require('settings.brackets')
require('plugins.filetree')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.lspzero')
require('plugins.lspsignature')
